config/routes.rb
Rails.application.routes.draw do

	devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get 'profile', to: 'users#profile', as: 'profile'
	get 'bonus', to: 'users#seagull', as: 'bonus'
	root to: 'posts#index'
    resources :posts
    resources :reports

end

app/models/admin.rb
class Admin < ApplicationRecord
	belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :topic
	belongs_to :user, optional: true
  	has_many :reports


	def self.search(search)
	  where("body LIKE :q OR title LIKE :q OR address LIKE :q OR street LIKE :q OR landlord LIKE :q", q: "%#{search}%")
	end
	
end

app/models/report.rb
class Report < ApplicationRecord

	belongs_to :user
	belongs_to :post

end

app/models/topic.rb
class Topic < ApplicationRecord

	has_many :posts
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :admins
  has_many :reports
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index

		@posts = Post.where(publish: true).paginate(:page => params[:page], :per_page => 15)
		@total_posts = Post.where(publish: true)
		@examples = @total_posts.sample(1)

		if params[:term].present?
			@posts = Post.where(publish: true).search(params[:term]).paginate(:page => params[:page], :per_page => 15)
			@total_posts = Post.where(publish: true).search(params[:term])
		end
		@post = Post.new
		@topics = Topic.all
	end

	def show
		@post = Post.find(params[:id])
		if @post.publish == false
			if @post.user == current_user
				redirect_to edit_post_path(@post)
			else
				redirect_to root_path
			end
		end
	end

	def create
		post_params = params[:post]
		post_params.permit!
		@post = Post.new
		@post.topic_id = post_params[:topic].to_i
		if user_signed_in?
			@post.user_id = current_user.id
		end
		@post.title = post_params[:title]
		@post.body = post_params[:body]
		@post.address = post_params[:address]
		@post.street = post_params[:street]
		@post.landlord = post_params[:landlord]
		if post_params[:publish].present?
			@post.publish = post_params[:publish]
		else
			@post.publish = true
		end
		respond_to do |format|
		    if @post.save
		      format.html  { redirect_to(@post,
		                    :notice => 'Post was successfully created.') }
		      format.json  { render :json => @post,
		                    :status => :created, :location => @post }
		    else
		      format.html  { render :action => "index" }
		      format.json  { render :json => @post.errors,
		                    :status => :unprocessable_entity }
		    end
		end
	end

	def edit
		@post = Post.find(params[:id])
		@topics = Topic.all
		
	end

	def update
		
	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	def new
		if !params[:post].present? or !user_signed_in?
			redirect_to root_path
		end
		@report = Report.new
		@post = Post.find(params[:post])

		@rep_topics = ["Inappropriate Language", "Violent/Threatening Content", "Suspected Falsehood", "Unintelligible", "Other"]
	
	end

	def create
		report_params = params[:report]
		@post = Post.find(params[:post_id])

		@report = Report.new
		@report.user = current_user
		@report.post_id = @post.id
		@report.topic = report_params[:topic]
		@report.body = report_params[:body]

		if @report.save
	      redirect_to(root_path, :alert => 'Report was successfully created.')
	    else

	      format.html  { render :action => "index" }
	      format.json  { render :json => @report.errors,
	                    :status => :unprocessable_entity }
	    end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def profile
		if !current_user.present?
			redirect_to root_path
		end
		@drafts = current_user.posts.where.not(publish: true)
		@published = current_user.posts.where(publish: true)
		@reports = Report.all
	end

	def seagull

	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def background_picker
		n = 1 #rand(1..3)
		if n == 1
			'image-background'
		elsif n == 2
			'image-background2'
		else
			'image-background3'
		end			
		
	end
end

app/helpers/posts_helper.rb
module PostsHelper
	def check_search
		params[:term]? "Filtered Stories" : "All Stories"	
	end

	def user_badge_generator
		if @post.user_id.present?			

			@user = User.find(@post.user_id)
			
			if @user == current_user
				
				if !current_user.admins.present?
					link_to edit_post_path(@post) do
						fa_icon "pencil", class: "text-secondary", data_toggle:"tooltip", title:"Edit Your Story"
					end
				end
			
			else
			
				fa_icon "user-plus", class: "text-success", data_toggle:"tooltip", title:"User Verified"
			
			end
		else
			fa_icon "user-times", class: "text-secondary", data_toggle:"tooltip", title:"Submitted Anonymously"
		end
	end

	def admin_badge_generator
		if user_signed_in?
			if current_user.admins.present?
				if @post.reports.present?
					link_to post_path(@post), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } do
						fa_icon "times", class: "text-danger", data_toggle:"tooltip", title:"Delete this Story"
					end
				
				else
					link_to edit_post_path(@post) do
						fa_icon "pencil", class: "text-secondary", data_toggle:"tooltip", title:"Edit this Story"
					end
				end
			end
		end
	end

	def flag_link(post_id)
		if user_signed_in?
			if !current_user.admins.present?
				link_to new_report_path(post: post_id) do
					fa_icon "flag", class: "text-danger", data_toggle:"tooltip", title:"Report Story"
				end
			else
				if @post.reports.present?
					link_to edit_post_path(@post) do
						fa_icon "pencil", class: "text-secondary", data_toggle:"tooltip", title:"Edit this Story"
					end
				end
			end
		else
			fa_icon "flag", class: "text-secondary", data_toggle:"tooltip", title:"Must Login to Report"
		end
	end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<div class="row">
    <div class="col-sm-offset-3 col-sm-6">

        <% if flash[:notice] %>
          <div class="alert alert-warning alert-dismissible show" role="alert">
            <%= flash[:notice] %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>

        <% if flash[:alert] %>
          <div class="alert alert-warning alert-dismissible show" role="alert">
            <%= flash[:alert] %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>

    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div class="row">

      <!-- Elements visible all the time -->
      <div class="col-sm-7">
         <%= render 'layouts/navigation/header' %>
      </div><!-- col-sm-7 -->

      <!-- Elements collapses on smaller devices -->
      <div class="col-sm-5">
        <%= render 'layouts/navigation/collapsible_elements' %>
      </div><!-- col-sm-5 -->

    </div><!-- row -->

  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VTU - Renters' Stories</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>
    
    <%= yield %>


  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<% if user_signed_in? %>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-right" id="links">
	  <ul class="nav navbar-nav ">
	    <li ><%= link_to current_user.email, profile_path %></li>
	    <li ><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
	  </ul>
	</div><!-- navbar-collapse -->
<% else %>
	
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-right" id="links">
	  <ul class="nav navbar-nav ">
	    <li ><%= link_to 'Login', new_user_session_path %></li>
	    <li ><%= link_to 'Signup', new_user_registration_path %></li>
	  </ul>
	</div><!-- navbar-collapse -->

<% end %>

app/views/layouts/navigation/_header.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#links" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to root_path do %>
	  <%= image_tag('favicon.ico', class: "navbar-brand") %>
  <% end %>
  <%= link_to "VTU - Renters' Stories", root_path, class: 'navbar-brand' %>
</div>

app/views/posts/_post.html.erb
<div class='col-sm-4'>
	  <div class="card" style="width: 100%;">
		  <div class="card-body">
		    <h5 class="card-title"><strong><%= post.title.truncate(20) %></strong></h5>
		    <h6 class="card-text text-muted text-right"><%= post.topic.name %></h6>
		    <div class='text-center btn-margin'>
			    <%= link_to('Full Story', post_path(post.id), class: "btn btn-dark") %> 
		    </div>
		  </div>
	  </div>
</div>

app/views/posts/edit.html.erb
<div class='container'>
  <div class='row text-center'>
    <div class='col-sm-offset-2 col-sm-8 col-sm-offset-2'>
      <div class='card'>
<%= form_for @post do |form| %>
	  
	  <label>Topic</label>
	  <%= form.select :topic, @topics.collect { |t| [ t.name, t.id.to_i ] }, {}, :class => 'form-control' %>
	  <label >Title</label>
	  <%= form.text_field :title, class: 'form-control', required: true %>
	  
	  <label>Post</label>
	  <%= form.text_area :body, style: 'width:100%; height:150px;', class: 'form-control', required: true %>
	  
	  <br/>
	  <button onclick="toggleOptions()" type="button" class='btn btn-dark'>Optional Inputs</button>
	  <br/><br/>
	  <div id='optional' class='form-group'>
	  	<h6 class='text-muted'>Note: Only share the following information if it has no potential to compromise your identity.</h6> 
		<label >Building Number</label>
		<%= form.number_field :address, class: 'form-control' %>
		<label >Street</label>
		<%= form.text_field :street, class: 'form-control' %>

	  	<h6 class='text-muted'>WARNING: Landlords may retaliate against tenants if a story provokes anger.</h6>
	  	<label >Landlord Name</label>
	  	<%= form.text_field :landlord, class: 'form-control' %>
	  	<h6 class='text-muted'>Use caution if you are providing any identifying information.</h6>
	  </div>
	  <% if user_signed_in? %>
	  	<div class='row'>
		  	<div class='col-sm-7'>
		  		<label class="checkbox">Publish Story?</label>
		  	</div>
		  	<div class='col-sm-5'>
	  			<%= form.check_box :publish, class: 'form-control' %>
		  	</div>
	  	</div>
	  	<h6 class='text-muted'>Unpublished Stories will be saved as drafts in your profile.</h6>
	  <% end %>
	  
	  <%= form.submit 'Save your story', :class => 'btn btn-dark form-control' %>
	<% end %>
	<br/>
        <%= link_to "Back", :back, class: "btn btn-dark" %>

	  </div>
	</div>
</div>
</div>


	<script type="text/javascript">
function toggleOptions() {
  var x = document.getElementById("optional");
  if (x.style.display == "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>

app/views/posts/index.html.erb
<div class=<%= background_picker %> >
    <%= render 'layouts/alerts' %>
	<div class='container'>

		<div class='row'>
			<div class='col-sm-3 text-center'>
				<div id='sidebar' class='card'>
					<%= render 'posts/index/sidebar' %>
				</div>
			</div>
			<div class='col-sm-9'>
				<div id='mainpage'>
					<%= render 'posts/index/mainpage' %>
				</div>
			</div>
		</div>

      <div class='card'>
        <div class='row'>
          <div class='col-sm-4'>
            <%= image_tag('logo.jpg') %>
          </div>
          <div class='col-sm-8 text-right root_footer_right'>
          	<p>Our struggle opposes colonial and patriarchical systems of oppression.</p>
            <p>We organize on the stolen territory of the səl̓ílwətaʔɬ/Selilwitulh (Tsleil-Waututh), Skwxwú7mesh Úxwumixw (Squamish), Stó:lō (Sto:lo) and xʷməθkʷəy̓əm (Musqueam) Nations.</p>
            <p>We must always remember that they were the first peoples displaced from this land and have been its caretakers since time immemorial.</p>
            <h3><strong>VTU - Renters' Stories</strong></h3>
          </div>
        </div>
      </div>
	</div>
	<div class='seagull'><p><%= link_to 'SEAGULL', bonus_path %></p></div>
</div>

app/views/posts/index/_mainpage.html.erb
<h3><strong>Feature Story:</strong></h3>
<% @examples.each do |p| %>
	<div class="card" style="width: 100%;">
	   <div class="card-body text-center">
	  	<div class='row'>
		  	<div class='col-sm-9'>
			    <h4 class="card-title"><strong><%= p.title %></strong></h4>
			    <h6 class="card-text"><strong><%= p.body.truncate(144) %><strong></h6>
			</div>
		  	<div class='col-sm-3'>
			    	<h6 class='text-muted'>Topic: <%= p.topic.name %></h6>
			    	<%= link_to('Read More', post_path(p.id), class: "btn btn-dark") %> 
			</div>
		</div>
	   </div>
	  </div>
<% end %>

<div class='row'>
	<div class='col-sm-3'>
		<h3><strong><%= check_search %></strong></h3><h6 class="text-muted">Total: <%= @total_posts.length %></h6>
	</div>
	<div class='col-sm-9'>
		<div class='row'>
			<br/>
			<div class='col-sm-8'>
				<%= form_tag posts_path, :method => 'get'  do %>
  					<%= text_field_tag :term, params[:term], class: "form-control" %>
			</div>
			<div class='col-sm-4'>
  					<%= submit_tag 'Search', :class => "form-control btn-special" %>
				<% end %>
			</div>
		</div>
	</div>

</div>

<div class='row'>
	<%= render @posts %>		
</div>
<% if @total_posts.length > 15 %>
	<div class='row'>
		<div class='col-sm-offset-3'>
		<div class='col-sm-8 card text-center'>
			<%= will_paginate @posts %>
		</div>
		</div>
	</div>
<% end %>

app/views/posts/index/_sidebar.html.erb
<h3><strong>What is your Renter's Story?</strong></h3>
<% if !user_signed_in? %>
	<h6 class='text-muted'>
		To edit your story after it is submitted or to save drafts before you publish, you must <%= link_to 'Login', "#" %>.
	</h6>
<% end %>
<div>
	<%= form_for @post do |form| %>
	  
	  <label>Topic</label>
	  <%= form.select :topic, @topics.collect { |t| [ t.name, t.id.to_i ] }, {}, :class => 'form-control' %>
	  <label >Title</label>
	  <%= form.text_field :title, class: 'form-control', required: true %>
	  
	  <label>Post</label>
	  <%= form.text_area :body, style: 'width:100%; height:150px;', class: 'form-control', required: true %>
	  
	  <br/>
	  <button onclick="toggleOptions()" type="button" class='btn btn-dark'>Optional Inputs</button>
	  <br/><br/>
	  <div id='optional' class='form-group'>
	  	<h6 class='text-muted'>Note: Only share the following information if it has no potential to compromise your identity.</h6> 
		<label >Building Number</label>
		<%= form.number_field :address, class: 'form-control' %>
		<label >Street</label>
		<%= form.text_field :street, class: 'form-control' %>

	  	<h6 class='text-muted'>WARNING: Landlords may retaliate against tenants if a story provokes anger.</h6>
	  	<label >Landlord Name</label>
	  	<%= form.text_field :landlord, class: 'form-control' %>
	  	<h6 class='text-muted'>Use caution if you are providing any identifying information.</h6>
	  </div>
	  <% if user_signed_in? %>
	  	<div class='row'>
		  	<div class='col-sm-7'>
		  		<label class="checkbox">Publish Story?</label>
		  	</div>
		  	<div class='col-sm-5'>
	  			<%= form.check_box :publish, class: 'form-control' %>
		  	</div>
	  	</div>
	  	<h6 class='text-muted'>Unpublished Stories will be saved as drafts in your profile.</h6>
	  <% end %>
	  
	  <%= form.submit 'Submit your story', :class => 'btn btn-dark form-control' %>
	<% end %>
</div>

<script type="text/javascript">
function toggleOptions() {
  var x = document.getElementById("optional");
  if (x.style.display == "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>

app/views/posts/show.html.erb
<div class='container text-center'>
	<div class='card'>
		<h3><strong><%= @post.title %></strong></h3>
	</div>
	<div class='row'>
		<div class='col-sm-6'>
			<% if @post.address.present? and @post.street.present? %>
				<div class='card'>
					<h6 class='text-muted'>Address: <%= @post.address %> <%= @post.street %></h6>
				</div>
			<% end %>
		</div>
		<div class='col-sm-6'>
			<% if @post.landlord.present? %>
				<div class='card'>
					<h6 class='text-muted'>Landlord: <%= @post.landlord %></h6>
				</div>
			<% end %>
		</div>
	</div>
	<h6><strong><%= @post.body %></strong></h6>
</div>
<div class='footer'>
	<div class='container text-center'>
		<div class='row'>
			<div class='col-sm-6'>
				<%= link_to root_path, class: 'btn btn-dark form-control footer-btn' do %>
					<%= fa_icon "home", text: "Home" %>
				<% end %>
			</div>
			<div class='col-sm-6'>
				<div class='card'>
					<h6 class='text-muted'><span data_toggle:"tooltip", title:"Topic"><%= @post.topic.name %> </span><%= user_badge_generator %><%= admin_badge_generator %><%= flag_link(@post.id) %></h6>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/reports/_report.html.erb
<div class='col-sm-4'>
	<h5><strong><%= report.topic %></strong></h5>
    <h6 class="card-text text-muted"><%= report.body.truncate(144) %></h6>
	<div class="card" style="width: 100%;">
	  <div class="card-body">
	    <h5 class="card-title"><strong><%= report.post.title.truncate(20) %></strong></h5>
	    <h6 class="card-text text-muted text-right"><%= report.post.topic.name %></h6>
	    <div class='text-center btn-margin'>
		    <%= link_to('Full Story', post_path(report.post.id), class: "btn btn-dark") %> 
	    </div>
	  </div>
    </div>
</div>

app/views/reports/new.html.erb
<div class='container'>
  <div class='row text-center'>
    <div class='col-sm-offset-4 col-sm-4 col-sm-offset-4'>
    	<h3><strong>Report a Story</strong></h3>
    	<p>Reporting: <%= link_to @post.title, post_path(@post) %></p>
		<%= form_for @report do |form| %>
		  <%= hidden_field_tag 'post_id', @post.id %>
		  
		  <label>Topic</label>
		  <%= form.select :topic, @rep_topics, {}, :class => 'form-control' %>

		  <label>Post</label>
		  <%= form.text_area :body, style: 'width:100%; height:150px;', class: 'form-control', required: true %>
		  <br/>
		  <%= form.submit 'Report this story', :class => 'btn btn-dark form-control' %>
		<% end %>
		<br/>
		<%= link_to "Back", post_path(@post), class: 'form-control btn btn-dark' %>
	</div>
  </div>
</div>

app/views/users/profile.html.erb
<div class=<% background_picker %> >
	<div class='container'>
		<div class='row'>
			<div class='col-sm-3 text-center'>
				<div id='sidebar' class='card'>
					<%= render 'users/profile/sidebar' %>
				</div>
			</div>
			<div class='col-sm-9'>
				<div id='mainpage'>
					<%= render 'users/profile/mainpage' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/profile/_mainpage.html.erb
<% if params[:page].present? %>
	<% if params[:page] == "stories" %>
		<h3><strong>Published</strong></h3>
		<% if @published.present? %>
			<div class='row'>
				<%= render @published %>
			</div>
		<% else %>
			<h6 class='text-muted'>
				No published stories yet. Submit one from the <%= link_to "Homepage", root_path %>
			</h6>
		<% end %>
	<% elsif params[:page] == "settings" %>
		<h3><strong>Settings</strong></h3>
			<%= link_to "Edit Account Info", edit_user_registration_path(current_user), class: 'btn btn-special form-control' %>
	<% elsif params[:page] == "admin" %>
		<% if Admin.where(user_id: current_user.id).present? %>
			<h3><strong>Admin</strong></h3>
			<%= render @reports %>
		<% end %>
	<% else %>
		<h3><strong>Error</strong></h3>
		<p>The page you've requested does not exist.</p>
	<% end %>
<% else %>
	<h3><strong>Drafts</strong></h3>
	<% if @drafts.present? %>
			<div class='row'>
				<%= render @drafts %>
			</div>
		<% else %>
			<h6 class='text-muted'>
				No saved drafts yet. Submit one from the <%= link_to "Homepage", root_path %>
			</h6>
		<% end %>
<% end %>

app/views/users/profile/_sidebar.html.erb
<h3><strong>Your Profile</strong></h3>
<h6 class='text-muted'>
		Menu
	</h6>
<p><%= link_to 'Drafts', profile_path, class: 'btn btn-dark form-control' %></p>
<p><%= link_to 'Published', profile_path(page: "stories"), class: 'btn btn-dark form-control' %></p>
<p><%= link_to 'Settings', profile_path(page: "settings"), class: 'btn btn-dark form-control' %></p>
<% if current_user.admins.length > 0 %>
	<p><%= link_to 'Admin', profile_path(page: "admin"), class: 'btn btn-dark form-control' %></p>
<% end %>

app/views/users/seagull.html.erb
<div class='container'>
	<div class='row text-center'>
    <div class='col-sm-offset-4 col-sm-4 col-sm-offset-4'>
	<div class='text-center card'>
		<h3><strong>~~ Ƨ&#600;∀&#1508;∩&#8515;˥ ~~</strong></h3>
		<%= image_tag('bonus.jpg') %>
		<h3><strong>~~  ~~  ~~</strong></h3>
		<%= link_to root_path, class: 'btn btn-dark' do %>
			<%= fa_icon "home", text: "Home" %>
		<% end %>
	</div>
	</div>
	</div>
</div>